# Generated by Django 4.2.5 on 2026-02-04 22:58

import apps.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_type', models.CharField(choices=[('owner', 'Property owner'), ('agent', 'Real-estate agent'), ('promoter', 'Property promoter'), ('customer', 'customer'), ('admin', 'Admin')], default='customer', max_length=50, verbose_name='User Type')),
                ('username', models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, verbose_name='username')),
                ('name', models.CharField(blank=True, default='', max_length=60, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(default='', max_length=50, null=True, verbose_name='phone number')),
                ('register_data', models.CharField(default='', max_length=20)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_image')),
                ('unique_no', models.SlugField(blank=True, unique=True, verbose_name='unique_no')),
                ('is_seller', models.BooleanField(default=False, verbose_name='Is Seller?')),
                ('device_token', models.CharField(blank=True, default='', max_length=255, verbose_name='Decive Token')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('line1', models.CharField(blank=True, default='', max_length=255, verbose_name='Line 1')),
                ('line2', models.CharField(blank=True, default='', max_length=255, verbose_name='Line 2')),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activite?')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='time_created')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='time_updated')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max Price')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min Price')),
                ('for_sale', models.BooleanField(default=True, verbose_name='For Sale?')),
                ('for_rent', models.BooleanField(default=True, verbose_name='For Rent?')),
            ],
            options={
                'db_table': 'Alarm',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('data_type', models.CharField(choices=[('string', 'String'), ('int', 'Number'), ('char', 'Char'), ('bool', 'Boolean'), ('date', 'Date'), ('float', 'Float')], max_length=50, verbose_name='data_type')),
            ],
            options={
                'db_table': 'Attribute',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='apps.category')),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='feature Name')),
            ],
            options={
                'db_table': 'Feature',
            },
        ),
        migrations.CreateModel(
            name='PrivateChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('connected_users', models.ManyToManyField(blank=True, related_name='connected_users', to=settings.AUTH_USER_MODEL)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PrivateChatRoom',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('size', models.IntegerField(verbose_name='size')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='time_created')),
                ('unique_number', models.SlugField(editable=False, verbose_name='unique_number')),
                ('for_sale', models.BooleanField(default=False, verbose_name='Is For sale')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is_featured')),
                ('for_rent', models.BooleanField(default=False, verbose_name='Is For Rent?')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='Last activet time')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='apps.address', verbose_name='Address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='apps.category', verbose_name='category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'Property',
            },
        ),
        migrations.CreateModel(
            name='Ticket_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
            ],
            options={
                'db_table': 'Ticket_status',
            },
        ),
        migrations.CreateModel(
            name='Ticket_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='type')),
            ],
            options={
                'db_table': 'Ticket_type',
            },
        ),
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=50, verbose_name='type')),
            ],
            options={
                'db_table': 'Type',
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone_num', models.CharField(blank=True, default='', max_length=50, verbose_name='user_phone_num')),
                ('random_code', models.CharField(max_length=4, verbose_name='random_code')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='time_created')),
                ('expire_date', models.DateTimeField(auto_now_add=True, verbose_name='expire_date')),
            ],
            options={
                'db_table': 'VerificationCode',
            },
        ),
        migrations.CreateModel(
            name='ValueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Value')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_attribute', to='apps.attribute', verbose_name='attribute')),
            ],
            options={
                'db_table': 'Value',
            },
        ),
        migrations.CreateModel(
            name='UnreadChatRoomMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('most_recent_message', models.CharField(blank=True, max_length=500, null=True)),
                ('reset_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='apps.privatechatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unread_message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UnreadChatRoomMessages',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Opened', 'Opened'), ('InProcess', 'In Process'), ('Reviewed', 'Reviewed')], default='Opened', max_length=100, verbose_name='Ticket_status')),
                ('phone_number', models.CharField(max_length=50, verbose_name='phone_number')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('solved_time', models.DateTimeField(blank=True, null=True, verbose_name='solved_time')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('problem_text', models.TextField(verbose_name='problem_text')),
                ('ticket_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_sender', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
                ('ticket_solver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_solver', to=settings.AUTH_USER_MODEL, verbose_name='solver')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket', to='apps.ticket_type', verbose_name='type')),
            ],
            options={
                'db_table': 'Ticket',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='apps.city', verbose_name='City')),
            ],
            options={
                'db_table': 'State',
            },
        ),
        migrations.CreateModel(
            name='Solve_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solve_message', to='apps.ticket', verbose_name='ticket')),
            ],
            options={
                'db_table': 'Solve_message',
            },
        ),
        migrations.CreateModel(
            name='RoomChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.privatechatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RoomChatMessage',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='time_created')),
                ('review', models.TextField(verbose_name='Note')),
                ('rate_review', models.FloatField(default=0.0, validators=[apps.models.validate_rate_range], verbose_name='Rating Number')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='apps.property', verbose_name='Property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='time_created')),
                ('note', models.TextField(verbose_name='Note')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='apps.property', verbose_name='property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'Report',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0.0, validators=[apps.models.validate_rate_range], verbose_name='Rating Number')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='time_created')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='apps.property', verbose_name='prperty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'Rate',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to=apps.models.generate_upload_to_path, verbose_name='Image')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FriendRequest',
            },
        ),
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FriendList',
            },
        ),
        migrations.CreateModel(
            name='Feature_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_category', to='apps.category', verbose_name='category')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_category', to='apps.feature', verbose_name='feature')),
            ],
            options={
                'db_table': 'Feature_category',
            },
        ),
        migrations.AddField(
            model_name='feature',
            name='cate',
            field=models.ManyToManyField(through='apps.Feature_category', to='apps.category', verbose_name='category'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='time_created')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='apps.property', verbose_name='prop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'Favorite',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='apps.country', verbose_name='Country'),
        ),
        migrations.CreateModel(
            name='Category_attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_attribute', to='apps.attribute', verbose_name='attribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_attribute', to='apps.category', verbose_name='category')),
            ],
            options={
                'db_table': 'Category_attribute',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('end_time', models.DateTimeField(verbose_name='end_time')),
                ('start_time', models.DateTimeField(verbose_name='start_time')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Title')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active status')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='apps.category', verbose_name='category')),
            ],
            options={
                'db_table': 'Banner',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Attribute_verify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50, verbose_name='attribute')),
                ('data_type', models.CharField(max_length=50, verbose_name='data_type')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.typemodel', verbose_name='type')),
            ],
            options={
                'db_table': 'Attribute_verify',
            },
        ),
        migrations.CreateModel(
            name='Attribute_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.attribute', verbose_name='attribute_value')),
            ],
            options={
                'db_table': 'Attribute_value',
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='category',
            field=models.ManyToManyField(blank=True, through='apps.Category_attribute', to='apps.category', verbose_name='categores'),
        ),
        migrations.CreateModel(
            name='Alarm_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Value')),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_value', to='apps.alarm', verbose_name='Alarm')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_value', to='apps.attribute', verbose_name='Attribute')),
            ],
            options={
                'db_table': 'Alarm_value',
            },
        ),
        migrations.AddField(
            model_name='alarm',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm', to='apps.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm', to='apps.state', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='value',
            field=models.ManyToManyField(through='apps.Alarm_value', to='apps.attribute', verbose_name='alarm_value'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='apps.state', verbose_name='State '),
        ),
        migrations.CreateModel(
            name='property_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_value', to='apps.property', verbose_name='property')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_value', to='apps.valuemodel', verbose_name='value')),
            ],
            options={
                'db_table': 'property_value',
                'unique_together': {('property', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Feature_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_property', to='apps.feature', verbose_name='Feature')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_property', to='apps.property', verbose_name='Property')),
            ],
            options={
                'db_table': 'Feature_property',
                'unique_together': {('property', 'feature')},
            },
        ),
    ]
